### ISSUE TITLE
IllegalArgumentException: baseUrl must end in /: https://flagsmith.mycompany.com/api/v1

### ISSUE THREAD

**Issue by LumisD** [Flagsmith/flagsmith-kotlin-android-client#26]
I updated this library from version 1.1.2 to version 1.2.2 and started to get crashes at the moment of initializaiton of flagsmith.

```
@Singleton
    @Provides
    fun provideFlagsmith(@ApplicationContext appContext: Context): Flagsmith {
        var fl: Flagsmith? = null
        try {
            fl = Flagsmith(
                environmentKey = BuildConfig.FLAGSMITH_KEY,
                baseUrl = "https://flagsmith.mycompany.com/api/v1",
                context = appContext
            )
            return fl
        } catch (e: Exception) {
            Log.d("qwer", "AppModulesProviders provideFlagsmith Exception: ${e.message}")
            throw Exception("Flagsmith crash")
        }
    }
```
Usually all body of this function is only `return Flagsmith(...)`  I added a try-catch to this inicialization to be sure that it happens exactly here. If I set version back 1.1.2 - it doesn't crash.
Environment: Android project written on Kotlin, Hilt is used for dependency injection

Full log (I only replaced actual company name on "mycompany" and another part on "something"):
```
2023-09-08 10:34:03.069 6357-6357/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mycompany.android.something, PID: 6357
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mycompany.android.something/com.mycompany.android.something.ui.main.MainActivity}: java.lang.IllegalArgumentException: baseUrl must end in /: https://flagsmith.mycompany.com/api/v1
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.IllegalArgumentException: baseUrl must end in /: https://flagsmith.mycompany.com/api/v1
        at ow.d0$b.b(Retrofit.java:56)
        at cb.a.<init>(Flagsmith.kt:14)
        at wm.i$a.get(DaggerNFCApplication_HiltComponents_SingletonC.java:997)
        at as.c.get(DoubleCheck.java:14)
        at wm.i$a.get(DaggerNFCApplication_HiltComponents_SingletonC.java:1005)
        at as.c.get(DoubleCheck.java:14)
        at wm.k.p0(DaggerNFCApplication_HiltComponents_SingletonC.java:7)
        at wm.k.k0(DaggerNFCApplication_HiltComponents_SingletonC.java:24)
        at wm.k$a.get(DaggerNFCApplication_HiltComponents_SingletonC.java:62)
        at xr.b$a.b(HiltViewModelFactory.java:47)
        at androidx.lifecycle.a.create(AbstractSavedStateViewModelFactory.kt:16)
        at xr.b.create(HiltViewModelFactory.java:15)
        at androidx.lifecycle.k1$b.create(ViewModelProvider.kt:2)
        at androidx.lifecycle.k1.b(ViewModelProvider.kt:65)
        at androidx.lifecycle.k1.a(ViewModelProvider.kt:24)
        at androidx.lifecycle.i1.getValue(ViewModelLazy.kt:40)
        at com.mycompany.android.something.ui.main.MainActivity.r(MainActivity.kt:3)
        at com.mycompany.android.something.ui.main.MainActivity.onCreate(MainActivity.kt:196)
        at android.app.Activity.performCreate(Activity.java:8290)
        at android.app.Activity.performCreate(Activity.java:8270)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8663) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```

**Comment by khvn26** [comment]
Hi @LumisD!

Please try initialising your client with a trailing slash at the end of your base URL, e.g.:

```java
            fl = Flagsmith(
                environmentKey = BuildConfig.FLAGSMITH_KEY,
                baseUrl = "https://flagsmith.mycompany.com/api/v1/",
                context = appContext
            )
```

Please let us know if the error persists.

**Comment by LumisD** [comment]
thanks, it works
