### ISSUE TITLE
Getting failure while retrieving feature flag on Android/kotlin Client

### ISSUE THREAD

**Issue by Nitin-UpSwing** [Flagsmith/flagsmith-kotlin-android-client#39]
result: Failure(java.lang.NullPointerException
                                                                                                    	com.github.kittinunf.fuel.core.FuelError$a.a(FuelError.kt:39)
                                                                                                    	com.github.kittinunf.fuel.core.FuelError$a.b(FuelError.kt:13)
                                                                                                    	t2.g.call(RequestTaskCallbacks.kt:53)
                                                                                                    Caused by: java.lang.NullPointerException
                                                                                                    	m2.b.o(Flagsmith.kt:90)
                                                                                                    	m2.a.k(Flagsmith.kt:39)
                                                                                                    	q2.g$a.k(Deserializable.kt:27)
                                                                                                    	q2.h.p(Deserializable.kt:19)
                                                                                                    	q2.y.run(Unknown Source:2)
                                                                                                    	q2.e$a.execute(Environment.kt:3)
                                                                                                    	q2.j.o(Deserializable.kt:52)
                                                                                                    	t2.g.call(RequestTaskCallbacks.kt:35)
                                                                                                    	java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	java.lang.Thread.run(Thread.java:1012)
                                                                                                    )

**Comment by matthewelwell** [comment]
Hi @Nitin-UpSwing, please can you provide more information here? Can you share your code which triggered this exception? Please provide as much information as you can! Please also remember to use backticks to create code blocks for formatting. 

Once we've got enough information to replicate, we will investigate this further.

**Comment by matthewelwell** [comment]
I see that you're using `v1.0.1`. Can you confirm if this issue is still there in `v1.4.0`?

**Comment by Nitin-UpSwing** [comment]
Hi @matthewelwell 
I have also tried you sample app for android kotlin :https://github.com/sbmaggarwal/Flagsmith-AndroidFeatureFlags
and this code also having same issue as I mentioned.

can you please let me know if I am doing anything wrong in integration [steps](https://github.com/Flagsmith/flagsmith-kotlin-android-client/issues/39#issuecomment-1840865930)?

**Comment by Nitin-UpSwing** [comment]
Hi @dabeeeenster while using v1.0.4 , I am getting below attached error when we initialized flag smit object:



`FATAL EXCEPTION: main
                                                                                                    Process: one.upswing.edhas, PID: 15379
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{one.upswing.edhas/one.upswing.edhas.ui.ExploreSdkActivity}: kotlin.UninitializedPropertyAccessException: lateinit property retrofit has not been initialized
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3967)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4112)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2527)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:223)
                                                                                                    	at android.os.Looper.loop(Looper.java:324)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8485)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
                                                                                                    Caused by: kotlin.UninitializedPropertyAccessException: lateinit property retrofit has not been initialized
                                                                                                    	at m2.b.<init>(Flagsmith.kt:145)
                                                                                                    	at one.upswing.edhas.ui.ExploreSdkActivity.onCreate(ExploreSdkActivity.kt:78)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8733)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8702)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3948)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4112) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2527) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:223) 
                                                                                                    	at android.os.Looper.loop(Looper.java:324) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8485) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)`
                                                                                                    	
                                                                                                    	
                                                                                                    	
Below are the steps I am using to integrate flagsmit:

app's builld.gralde dependency
`implementation 'com.github.Flagsmith:flagsmith-kotlin-android-client:1.4.0'`
Project level build.gradle
`maven { url "https://jitpack.io" }`

in Activity's onCreate function
```
val flagsmith = Flagsmith(environmentKey = "Uoo5YF76zoWec9zyigDZkH", context = this, enableAnalytics = true)
  flagsmith.getValueForFeature("td_amount") { result ->
                    Log.d("Flagsmith", "result: $result")
                    Log.d("Flagsmith", "result: ${result.isFailure}")
                    Toast.makeText(this, "TD Amount: $result", Toast.LENGTH_LONG).show()
                }

```

**Comment by dabeeeenster** [comment]
> Hi @dabeeeenster while using v1.0.4

`1.0.4` or `1.4.0`?

**Comment by JamieMasonWright** [comment]
Can you please take this email off. I cannot unsubscribe and keep receiving your updates| Thank you

**Comment by Nitin-UpSwing** [comment]
Hi @dabeeeenster 
can you please help me by when I can able use the flag smith without any issue?
